### ISSUE TITLE
Blank response for "show"

### ISSUE THREAD

**Issue by arhoads76** [univ-of-utah-marriott-library-apple/display_manager#23]
I'm not sure what's causing this.  I'm running macOS Catalina.  When I run the "show" command I get nothing.

% ./display_manager.py show
%

Thoughts?

**Comment by arhoads76** [comment]
It looks like a permission issue for iTerm.  It worked fine when I tried it with Terminal.

**Comment by uurazzle** [comment]
Hi @arhoads76:

Sorry, you are having issues. Do you have python installed? Which version?

`python --version`

This project was developed against python 2.7, so, python 3.x might have issues and it's hasn't been a priority and we haven't had time to test against newer python releases.
