### ISSUE TITLE
Setting the primary display

### ISSUE THREAD

**Issue by flammable** [univ-of-utah-marriott-library-apple/display_manager#3]
Thank you so much for this!  It's really helped with an issue we've been having in one of our computer labs - the professor wanted mirroring disabled when a user logs in, so deploying this alongside a script run with [outset](https://github.com/chilcote/outset) seemed to do the trick.

Unfortunately, running this command at login:

`/usr/local/bin/display_manager.py mirroring disable`

has the side effect of making the wrong monitor the primary display - the Mac is connected to a TV, and the TV is always set as the primary display.  Is there a way to override that with Display Manager?  I tried a few command combinations but none of them would change this - for example, `set highest` turns off mirroring, bumps up the resolution of each display, but leaves the (wrong) primary display intact.

If it's not something Display Manager supports, but you know of a different way to script this, I'd really appreciate it.  Thanks!

Mike

**Comment by SamBaRufus** [comment]
Mike,

I have also noticed some issues as well and have taken over the development for this script to work out some of these bugs. I will add this to the list.

**Comment by flammable** [comment]
Thank you, Sam!

Mike

**Comment by ahdavies6** [comment]
Mike,

We've performed a total overhaul of the script. v1.0.0 requires a new syntax, but should be able to do exactly what you've requested without any problems. Let us know if you run into any other problems with the updated script.

Best,
Adam

**Comment by flammable** [comment]
Thanks, @ahdavies6! I'll experiment once the semester starts. Things are a bit crazy for us right now, as I'm sure is the case for you, too. :)

**Comment by uurazzle** [comment]
@flammable Any status on testing the update of Display Manager? When you get time, please test and reply back with status.

**Comment by flammable** [comment]
@uurazzle Hey Richard, unfortunately things are still really busy at work. I'll need to get into a classroom and try the new script. I'm sure this is a major improvement over my hacked-together solution that involved the previous iteration of this script in combination with cscreen!

**Comment by uurazzle** [comment]
k, np. Just wanted to make sure it was working properly for your environment. When you have time to test, please give us feedback either way (working or not working) or if you have any feature requests.
