### ISSUE TITLE
Best way to use this code in a separate module

### ISSUE THREAD

**Issue by Kalmat** [univ-of-utah-marriott-library-apple/display_manager#31]
Hi! Thank you so much for your work and for sharing it!

I am working on a new module aimed to get info and control monitors (specially in multi-monitor setups). You can check it [here](https://github.com/Kalmat/PyMonCtl) if you are curious. Struggling with macOS I found your module very useful but, since it is not available on PyPi (I already read in a reply of yours that it is not planned), I was wondering the best way to integrate it into my own module. I just need the rotation and brightness functions (no way to also deal with contrast and scale, there is?), but I felt that I had to ask before just copy-pasting the related code or the display_manager_lib.py file (of course, adding the license in all cases).

Thanks in advance!

**Comment by uurazzle** [comment]
Hi @Kalmat:

Sure, that is fine to include our code, just make sure we are given credit.

**Comment by Kalmat** [comment]
Thank you guys!

If, by chance, you find a way to deal with the contrast and/or turning the monitors on/off in macOS, please let me know!
