### ISSUE TITLE
README.md needs to be updated and minor Markdown fix

### ISSUE THREAD

**Issue by tjluoma** [univ-of-utah-marriott-library-apple/display_manager#5]
Under “Get Started“ it says:

`Next, download the latest installer [here](./versions/Display Manager v1.0.0.dmg), `

1. The Markdown stuff is showing 

2. That's not the latest installer anymore.

**Comment by ahdavies6** [comment]
@tjluoma:
Thank you for bringing this to our attention. The issue has been resolved.
